#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./homeassistant-frontend/src" ]; then
  cd homeassistant-frontend
  git submodule init
  git submodule update
  cd ..
fi

if [ ! -d "./insteon_frontend"]; then
  mkdir insteon_frontend
fi

rm -f yarn.lock
node ./script/merge_requirements.js
yarn install