#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./homeassistant-frontend/src" ]; then
  echo "Cloning into homeassistant-frontend submodule"
  git config --add safe.directory ./homeassistant-frontend
  git submodule update --init
fi

./homeassistant-frontend/.devcontainer/post_create.sh