#!/bin/sh
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
version=$1
if [ ! version ]; then
  echo You must enter a version number
  exit
fi
set -e

cd "$(dirname "$0")/.."

echo Updating frontend
cd homeassistant-frontend
git fetch origin
git checkout $version

cd ..
echo removing yarn.lock
# rm -f yarn.lock

echo merging requirements
node ./script/merge_requirements.js

echo installing modules
yarn install